# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
version=1.0.0

# Dependencies
# The Arcade version bundled in Server Replay 3.3.1+1.21.11
arcade_version=0.8.1-beta.37+1.21.11
